name: Generate Table of Contents

on:
  push:
    branches:
      - '**' # Trigger on push to any branch

jobs:
  generate-toc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate TOC
      uses: actions/markdown-toc@v1
      with:
        # Optional: Provide additional configurations here if needed
        # Example: file_glob: "docs/**/*.md"
        # By default, it will process all markdown files in the repo
