
On:
  Push:
    Branches:
-	‘**’

Jobs:
  Generate-toc:
    Runs-on: ubuntu-latest

    Steps:
-	Name: Checkout repository
      Uses: actions/checkout@v3

-	Name: Generate Table of Contents
      Uses: technote-space/toc-generator@v4
      With:
        TARGET_PATHS: ‘docs/**/*.md’
        COMMIT_MESSAGE: ‘docs: auto-generate TOC’
